name: Construire l'APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
      # Le SDK Android est déjà présent sur les machines GitHub (ANDROID_HOME)
      - name: Compiler
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          chmod +x gradlew
          ./gradlew assembleRelease --stacktrace
      - uses: actions/upload-artifact@v5
        with:
          name: PongDuo-apk
          path: app/build/outputs/apk/release/*.apk
